name: Verify samples DEV

on:
#  schedule:
#    - cron: '30 5 * * 1,4' # 5:30 UTC Mon, Thu
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Run a verifier
        uses: vmishenev/kotlin-samples-pusher@dev
        with:
          push-repository: 'https://github.com/vmishenev/kotlin-compiler-server'
          snippet-flags: 'kotlin'
          push-path: 'src/test/resources/test-compile-data/kotlin-web-site'
          username: '${{ secrets.TOKEN }}' #token with an access to create PR in push-repository and issue in this repository