name: 'Kotlin Samples Verifier'
description: 'Extracts embedded code snippets from HTML and Markdown files from a remote git repository, runs them and collects results into a repository of samples. It creates a issue for failed snippets.'
inputs:
  #options for work through cli
  repository:
    description: 'Git repository URL with samples to execute'
    required: false
    default: 'https://github.com/${{github.repository}}'
  verify-branch:
    description: 'git branch of repository to be verified'
    required: false
    default: '${{ github.ref }}'
  start-commit:
    description: 'Considering only the changed files starting with this'
    required: false
    default: ''
  end-commit:
    description: 'Considering only the changed files ending this'
    required: false
    default: ''
  #options for parsing
  snippet-flags:
    description: 'Flags for code snippets, separated by "," like so: "attr1,attr2"'
    required: false
    default: ''
  tag-filter:
    description: 'User filter for tag containing snippet  like so: (#tag="name" & attr1="val"). It also supports !, &, | operations.'
    required: false
    default: ''
  ignore-tag-filter:
    description: 'User filter for ignoring of tag including inners tags.'
    required: false
    default: ''
  #options for Pusher
  push-repository:
    description: 'Git repository URL to push the samples'
    required: true
  push-path:
    description: 'Path relatively a push repository'
    required: false
    default:  ''
  username:
    description: 'Username or access token for push'
    required: true
  password:
    description: 'User password for push'
    required: false
    default:  ''
  config-path:
    description: 'Url or file path for loading config'
    required: false
    default: 'config.properties'
  template-path:
    description: 'Url or file path for loading templates'
    required: false
    default: 'templates'
  severity:
    description: 'Create issue and do not push if the snippet has errors equals or greater the severity'
    required: false
    default: 'ERROR'

  io-event:
    description: 'The default is the event name (automatic mode). It needs to process the github events'
    required: false
    default: '${{ github.event_name }}'
runs:
  using: "composite"
  steps:
    #    - name: Set up JDK
    #      uses: actions/setup-java@v1
    #      with:
    #      java-version: 15
    - id: clone-compiler-server
      working-directory: ${{ github.action_path }}
      run: git clone https://github.com/AlexanderPrendota/kotlin-compiler-server --branch master --single-branch kotlin-compiler-server-build
      shell: bash
    - id: build-compiler-server
      working-directory: ${{ github.action_path }}/kotlin-compiler-server-build
      run: chmod +x gradlew; ./gradlew build -x test
      shell: bash
    - id: run-compiler-server
      working-directory: ${{ github.action_path }}/kotlin-compiler-server-build
      run: java -jar build/libs/kotlin-compiler-server-*.jar &
      shell: bash
    - id: install-dist
      working-directory: ${{ github.action_path }}
      run: ./gradlew installDist
      shell: bash
    - working-directory: ${{ github.action_path }}
      env:
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: echo "$GITHUB_EVENT" | ./build/install/kotlin-samples-pusher/bin/kotlin-samples-pusher -io-event '${{ inputs.io-event }}' -r ${{  inputs.repository }} -br ${{  inputs.verify-branch }} -snippet-flags '${{  inputs.snippet-flags }}' -tag-filter '${{  inputs.tag-filter }}' -ignore-tag-filter '${{  inputs.ignore-tag-filter }}' -push-repository ${{  inputs.push-repository }} -push-path '${{ inputs.push-path }}' -username ${{  inputs.username }} -passw '${{  inputs.password }}' -commits ${{  inputs.start-commit }},${{  inputs.end-commit }} -config-path '${{  inputs.config-path }}' -template-path '${{  inputs.template-path }}'
      shell: bash

