name: 'Kotlin Samples Verifier'
description: 'Extracts embedded code snippets from HTML and Markdown files from a remote git repository, runs them and collects results into a repository of samples. It creats a issue for failed snippets.'
inputs:
  repository:
    description: 'Git repository URL with samples to execute'
    required: true
  verify-branch:
    description: 'git branch of repository to be verified'
    required: false
    default: 'master'
  snippet-flags:
    description: 'Flags for code snippets, separated by "," like so: "attr1,attr2"'
    required: true
  start-commit:
    description: 'Considering only the changed files starting with this'
    required: false
    default: ''
  end-commit:
    description: 'Considering only the changed files ending this'
    required: false
    default: ''
  #options for Pusher
  push-repository:
    description: 'Git repository URL to push the samples'
    required: true
  push-path:
    description: 'Path relatively a push repository'
    required: false
    default:  ''
  username:
    description: 'Username or access token for push'
    required: true
  password:
    description: 'User password for push'
    required: false
    default:  ''
runs:
  using: "composite"
  steps:
    #    - name: Set up JDK
    #      uses: actions/setup-java@v1
    #      with:
    #      java-version: 15
    - id: docker-run
      working-directory: ${{ github.action_path }}
      run: ./gradlew dockerRun
      shell: bash
    - id: install-dist
      working-directory: ${{ github.action_path }}
      run: ./gradlew installDist
      shell: bash
    - working-directory: ${{ github.action_path }}
      run: ./build/install/kotlin-samples-pusher/bin/kotlin-samples-pusher -r ${{  inputs.repository }} -br ${{  inputs.verify-branch }} -snippet-flags ${{  inputs.snippet-flags }} -push-repository ${{  inputs.push-repository }} -path '${{ inputs.push-path }}' -username ${{  inputs.username }} -passw '${{  inputs.password }}' -commits ${{  inputs.start-commit }},${{  inputs.end-commit }}
      shell: bash

