name: Java CI with Gradle

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_bintrayUser: ${{ secrets.BINTRAY_USER }}
          ORG_GRADLE_PROJECT_bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew build publishToMavenLocal bintrayUpload